title: My first blog
author: Vitaliy Rev
email: revit2005@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My blog page. Check it out!

# social links
twitter_username: TrueMLGPro1 # DO NOT include the @ character, or else the build will fail!
github_username: vitaliy-rev # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
